<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.12.5 on win32)" generated="2025-05-06T14:42:36.062183" rpa="false" schemaversion="5">
<suite id="s1" name="FonctionnaliteMaps" source="C:\Users\bahae\Desktop\PfeProject\test_cases\FonctionnaliteMaps.robot">
<kw name="Démarrer Driver" type="SETUP">
<kw name="Setup Driver" owner="Integration">
<msg time="2025-05-06T14:42:40.929957" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAD87C0E0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session</msg>
<msg time="2025-05-06T14:42:42.959650" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2B6B0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session</msg>
<msg time="2025-05-06T14:42:44.976796" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2B9B0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session</msg>
<msg time="2025-05-06T14:42:47.002661" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2BC50&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</msg>
<var>${driver}</var>
<arg>${Device}</arg>
<doc>Initialise et retourne le driver Appium.</doc>
<status status="FAIL" start="2025-05-06T14:42:38.897913" elapsed="8.108750">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2BC50&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</status>
</kw>
<kw name="Set Suite Variable" owner="BuiltIn">
<arg>${driver}</arg>
<doc>Makes a variable available everywhere within the scope of the current suite.</doc>
<status status="NOT RUN" start="2025-05-06T14:42:47.006663" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2025-05-06T14:42:38.897913" elapsed="8.108750">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2BC50&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</status>
</kw>
<test id="s1-t1" name="Test Ouvrir Gps" line="38">
<status status="FAIL" start="2025-05-06T14:42:47.006663" elapsed="0.001000">Parent suite setup failed:
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2BC50&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</status>
</test>
<test id="s1-t2" name="Test GPS Location Functionality" line="76">
<doc>Teste la fonctionnalité de modification de position GPS
- Définit une position GPS spécifique via ADB
- Vérifie que la position a bien été mise à jour
- Tolère les échecs partiels avec continuation du test</doc>
<tag>gps</tag>
<status status="FAIL" start="2025-05-06T14:42:47.007663" elapsed="0.000000">Parent suite setup failed:
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2BC50&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</status>
</test>
<kw name="Fermer Driver" type="TEARDOWN">
<kw name="Close Driver" owner="Integration">
<msg time="2025-05-06T14:42:47.008663" level="FAIL">Variable '${driver}' not found.</msg>
<arg>${driver}</arg>
<doc>Ferme proprement le driver Appium.</doc>
<status status="FAIL" start="2025-05-06T14:42:47.007663" elapsed="0.001000">Variable '${driver}' not found.</status>
</kw>
<status status="FAIL" start="2025-05-06T14:42:47.007663" elapsed="0.001000">Variable '${driver}' not found.</status>
</kw>
<doc>Tests de fonctionnalité GPS pour appareil Android
- Vérification de la modification de position GPS
- Utilisation des commandes ADB pour contrôler l'émulateur</doc>
<status status="FAIL" start="2025-05-06T14:42:36.064184" elapsed="10.944479">Suite setup failed:
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2BC50&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))

Also suite teardown failed:
Variable '${driver}' not found.</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">gps</stat>
</tag>
<suite>
<stat name="FonctionnaliteMaps" id="s1" pass="0" fail="2" skip="0">FonctionnaliteMaps</stat>
</suite>
</statistics>
<errors>
<msg time="2025-05-06T14:42:40.929957" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAD87C0E0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session</msg>
<msg time="2025-05-06T14:42:42.959650" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2B6B0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session</msg>
<msg time="2025-05-06T14:42:44.976796" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000021EAEB2B9B0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session</msg>
</errors>
</robot>
